name: Link issue to Milestone

on:
  issues:
    types: [closed]

jobs:
  link:
    runs-on: ubuntu-22.04

    steps:
    - name: Link issue to milestone
      env:
        GH_TOKEN: ${{ secrets.REPOREADING_TOKEN }}
        repo: ${{ GITHUB.REPOSITORY }}
        issue: ${{ github.event.issue.number }}
      run: curl -s https://raw.githubusercontent.com/untillpro/ci-action/main/scripts/linkmilestone.sh | bash

